# Generated by Django 3.2.9 on 2021-11-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211120_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
    ]
